import { flexPayzTokens } from "./tokens";

export const flexPayzCssVariables = {
  "--fp-color-canvas": flexPayzTokens.color.background.canvas,
  "--fp-color-background-secondary": flexPayzTokens.color.background.secondary,
  "--fp-color-surface-primary": flexPayzTokens.color.surface.primary,
  "--fp-color-white": flexPayzTokens.color.surface.white,
  "--fp-color-surface-sand": flexPayzTokens.color.surface.sand,
  "--fp-color-champagne-soft": flexPayzTokens.color.surface.champagneSoft,
  "--fp-color-ink": flexPayzTokens.color.text.primary,
  "--fp-color-text-muted": flexPayzTokens.color.text.muted,
  "--fp-color-text-faint": flexPayzTokens.color.text.faint,
  "--fp-color-border": flexPayzTokens.color.border.subtle,
  "--fp-color-champagne": flexPayzTokens.color.accent.champagne,
  "--fp-color-champagne-dark": flexPayzTokens.color.accent.champagneDark,
  "--fp-color-success": flexPayzTokens.color.status.success,
  "--fp-color-success-soft": flexPayzTokens.color.status.successSoft,
  "--fp-color-danger": flexPayzTokens.color.status.danger,
  "--fp-font-ui": flexPayzTokens.typography.family.ui,
  "--fp-font-display": flexPayzTokens.typography.family.display,
  "--fp-font-family-display": flexPayzTokens.typography.family.display,
  "--fp-font-mono": flexPayzTokens.typography.family.mono,
  "--fp-font-size-caption": flexPayzTokens.typography.size.caption,
  "--fp-font-size-body-small": flexPayzTokens.typography.size.bodySmall,
  "--fp-font-size-body": flexPayzTokens.typography.size.body,
  "--fp-font-size-body-large": flexPayzTokens.typography.size.bodyLarge,
  "--fp-font-size-title-small": flexPayzTokens.typography.size.titleSmall,
  "--fp-font-size-title": flexPayzTokens.typography.size.title,
  "--fp-font-size-heading": flexPayzTokens.typography.size.heading,
  "--fp-font-size-display": flexPayzTokens.typography.size.display,
  "--fp-line-height-tight": String(flexPayzTokens.typography.lineHeight.tight),
  "--fp-line-height-heading": String(flexPayzTokens.typography.lineHeight.heading),
  "--fp-line-height-body": String(flexPayzTokens.typography.lineHeight.body),
  "--fp-line-height-control": String(flexPayzTokens.typography.lineHeight.control),
  "--fp-space-0": flexPayzTokens.spacing[0],
  "--fp-space-1": flexPayzTokens.spacing[1],
  "--fp-space-2": flexPayzTokens.spacing[2],
  "--fp-space-3": flexPayzTokens.spacing[3],
  "--fp-space-4": flexPayzTokens.spacing[4],
  "--fp-space-5": flexPayzTokens.spacing[5],
  "--fp-space-6": flexPayzTokens.spacing[6],
  "--fp-space-7": flexPayzTokens.spacing[7],
  "--fp-space-8": flexPayzTokens.spacing[8],
  "--fp-space-10": flexPayzTokens.spacing[10],
  "--fp-space-12": flexPayzTokens.spacing[12],
  "--fp-space-16": flexPayzTokens.spacing[16],
  "--fp-space-20": flexPayzTokens.spacing[20],
  "--fp-space-24": flexPayzTokens.spacing[24],
  "--fp-radius-xs": flexPayzTokens.radius.xs,
  "--fp-radius-sm": flexPayzTokens.radius.sm,
  "--fp-radius-md": flexPayzTokens.radius.md,
  "--fp-radius-lg": flexPayzTokens.radius.lg,
  "--fp-radius-xl": flexPayzTokens.radius.xl,
  "--fp-shadow-raised": flexPayzTokens.shadow.raised,
  "--fp-shadow-floating": flexPayzTokens.shadow.floating,
  "--fp-shadow-champagne": flexPayzTokens.shadow.champagne,
  "--fp-transition-fast": flexPayzTokens.transition.fast,
  "--fp-transition-standard": flexPayzTokens.transition.standard,
  "--fp-transition-slow": flexPayzTokens.transition.slow,
  "--fp-focus-ring": flexPayzTokens.focus.ring,
  "--fp-focus-outline": flexPayzTokens.focus.outline,
  "--fp-focus-offset": flexPayzTokens.focus.offset,
  "--fp-size-interactive-min": flexPayzTokens.size.interactiveMin,
} as const;

export type FlexPayzCssVariableName = keyof typeof flexPayzCssVariables;
